[env:midilord]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    ; fortyseveneffects/MIDI Library@^5.0.2
    fmalpartida/LiquidCrystal@^1.5.0
    fastled/FastLED@^3.6.0
    ; ; AsyncTCP and ESPAsyncWebServer for the config web server
    ; https://github.com/me-no-dev/AsyncTCP.git
    ; https://github.com/me-no-dev/ESPAsyncWebServer.git
    ; ; ArduinoJson for preset storage / web API
    ; bblanchon/ArduinoJson@^7.0.0
